version: '3.9'
services:
  front:
    build:
      context: ./
      dockerfile: dockerfile
    command: npm run docker
    volumes:
      - ./:/app
      - modules_front:/app/node_modules
    ports:
      - 3000:3000
    networks:
      - default
    env_file: .env
volumes:
  modules_front: {}
