version: '3.9'
services:
  node:
    build:
      context: ./
      dockerfile: dockerfile
    ##command: 'npm start'
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      ##- ${REACT_APP_PORT}:3000
      - 3000:3000
    networks:
      - default
    env_file: .env
