const GAME_ROCK = 'game:ROCK';
const GAME_SCISSORS = 'game:SCISSORS';
const GAME_PAPER = 'game:PAPER';
const GAME_ROCK_SCISSORS_PAPER_START = 'game:ROCK_SCISSORS_PAPER_START';
const GAME_ROCK_SCISSORS_PAPER_END = 'game:ROCK_SCISSORS_PAPER_END';
const GAME_ROCK_SCISSORS_PAPER_CANCEL = 'game:ROCK_SCISSORS_PAPER_CANCEL';
const GAME_ROCK_SCISSORS_PAPER_CHOICE = 'game:ROCK_SCISSORS_PAPER_CHOICE';
const GAME_ROCK_SCISSORS_PAPER_RESULT = 'game:ROCK_SCISSORS_PAPER_RESULT';
const GAME_ROCK_SCISSORS_PAPER_CHOICES = [GAME_ROCK, GAME_SCISSORS, GAME_PAPER];

const DUEL_REMOVE_LIFE = 'duel:removeLife';



// LISTENERS
const DUEL_CONNECTED = "duel:connected";

export default {
  GAME_ROCK_SCISSORS_PAPER_START,
  GAME_ROCK_SCISSORS_PAPER_END,
  GAME_ROCK_SCISSORS_PAPER_CANCEL,
  GAME_ROCK_SCISSORS_PAPER_CHOICE,
  GAME_ROCK_SCISSORS_PAPER_RESULT,
  GAME_ROCK_SCISSORS_PAPER_CHOICES,
  DUEL_REMOVE_LIFE,
  DUEL_CONNECTED
};
