const ROCK = Symbol('ROCK');
const SCISSORS = Symbol('SCISSORS');
const PAPER = Symbol('PAPER');
const ROCK_SCISSORS_PAPER_START = Symbol('ROCK_SCISSORS_PAPER_START');
const ROCK_SCISSORS_PAPER_END = Symbol('ROCK_SCISSORS_PAPER_END');
const ROCK_SCISSORS_PAPER_CANCEL = Symbol('ROCK_SCISSORS_PAPER_CANCEL');
const ROCK_SCISSORS_PAPER_CHOICE = Symbol('ROCK_SCISSORS_PAPER_CHOICE');
const ROCK_SCISSORS_PAPER_RESULT = Symbol('ROCK_SCISSORS_PAPER_RESULT');
const ROCK_SCISSORS_PAPER_CHOICES = [ROCK, SCISSORS, PAPER];

export {
  ROCK,
  SCISSORS,
  PAPER,
  ROCK_SCISSORS_PAPER_START,
  ROCK_SCISSORS_PAPER_END,
  ROCK_SCISSORS_PAPER_CANCEL,
  ROCK_SCISSORS_PAPER_CHOICE,
  ROCK_SCISSORS_PAPER_RESULT,
  ROCK_SCISSORS_PAPER_CHOICES,
};
